---
- name: Add keyserver to apt for Postgres
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8


- name: Add custom Postgres repo to apt to Latest version
  lineinfile: dest=/etc/apt/sources.list.d/pgdg.list
              line="deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" state=present create=yes
  notify: update apt cache


- meta: flush_handlers


- name: Installing apt packages i.e python, postgres, nginx, git etc
  apt: name={{item}}
  with_items:
      - python3-pip
      - python3-dev
      - libpq-dev
      - python-software-properties
      - software-properties-common
      - python3-psycopg2
      - postgresql
      - postgresql-contrib
      - git
      - nginx



- name: install python virtualenv and uWSGI using PIP3
  pip: executable=pip3 name={{item}}
  with_items:
        - virtualenv
        - uwsgi
